version: '3.9'

services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - backend_storage:/app/storage
    ports:
      - "8083:80"
    labels:
      traefik.enable: false # Disabled since we use manual Nginx
    networks:
      - default
      - web
    env_file:
      - .env

  db:
    image: percona:8.0
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-cattr}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-password}
    cap_add:
      - SYS_NICE
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '--password=${DB_PASSWORD:-password}', '-u', 'root']
      timeout: 20s
      retries: 10

volumes:
  backend_storage: {}
  database: {}

networks:
  default: {}
  web:
    driver: bridge
